### ISSUE TITLE
it does not seem to be valid extension

### ISSUE THREAD

**Issue by racinmat** [Z-nonymous/sd_webui_batchscripts#3]
Hi, I found https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7852 and I like it, but it's just so close to being valid extension, installable from the web UI. Should I make a PR with needed changes?

**Comment by Z-nonymous** [comment]
Hi @racinmat 
Thanks for the PR 👍 
I thought making it an extension would be overkill and be more complex, but it seems pretty straightforward from your PR...
And you made a fix for batchscriptA.py 👍
