### ISSUE TITLE
Not working in WebUI 1.3.2

### ISSUE THREAD

**Issue by Trevor-Z** [Z-nonymous/sd_webui_batchscripts#7]
On AUTOMATIC1111' WebUI 13.2, I choose batchimagesA.py, paste a txt with the address for two images with embedded prompts, select override model, run, and get the following error:

![Screenshot 2023-06-10 135359](https://github.com/Z-nonymous/sd_webui_batchscripts/assets/13950948/fa950a16-9c14-4fc8-806e-b2eac4432393)

**Comment by Z-nonymous** [comment]
What do you mean with "address" for the two images ?
These should be path (from local filesystem).
Can you share the syntax of your input file ?

**Comment by Z-nonymous** [comment]
Oh I see, I didn't read properly the error message, it seems your image contains a "Version" parameter that is not expected.

There's a quick fix to add:
```
 'Version': 'skip-14',
```
in the definition of `arg_mapping` in [scripts/script_common.py](https://github.com/Z-nonymous/sd_webui_batchscripts/blob/main/scripts/script_common.py)

However, I need to figure out a more elegant way to get rid of unsupported parameters.

**Comment by Z-nonymous** [comment]
@Trevor-Z 
Should be working with the latest update.
